[versions]
jvm = "11"
kotlin = "1.8.10"
compose = "1.3.1"
android = "7.4.2"
android-sdk-compile = "33"
android-sdk-min = "26"
android-sdk-target = "33"

[libraries]
androidx-appcompat = "androidx.appcompat:appcompat:1.5.1"
androidx-core-ktx = "androidx.core:core-ktx:1.8.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.5.0"

[bundles]

[plugins]
kotlin-mpp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "android" }
