name: Prepare for slides
description: Prepare for slides

runs:
  using: "composite"
  steps:

    - name: Install java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        java-package: jdk+fx
        distribution: zulu

    - name: Install graphviz
      shell: bash
      run: sudo apt-get install -y graphviz

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Configure
      shell: bash
      run: ./gradlew --stacktrace help
