name: Build for Web
description: Build for Web

runs:
  using: "composite"
  steps:

    - name: Build for Web
      shell: bash
      run: ./gradlew --stacktrace :web-app:jsBrowserDistribution

    - name: Upload web HTDOCS
      uses: actions/upload-artifact@v3
      with:
        name: imaginate-web-htdocs
        path: applications/web-app/build/dist/js/productionExecutable
        if-no-files-found: error
