name: Build for Android
description: Build for Android

runs:
  using: "composite"
  steps:

    - name: Build for Android
      shell: bash
      run: ./gradlew --stacktrace :android-app:assembleDebug
