name: Prepare for build
description: Prepare for build

runs:
  using: "composite"
  steps:

    - name: Install java
      uses: actions/setup-java@v3
      with:
        java-version: 17
        java-package: jdk+fx
        distribution: zulu

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Configure
      shell: bash
      run: ./gradlew --stacktrace --dry-run build
