name: Publish Slides

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:

  wrapper_validation:
    name: "Wrapper Validation"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v1

  publish_slides:
    name: Publish Slides
    needs: wrapper_validation
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SLIDES_SSH_DEPLOY_KEY }}

      - name: Prepare for slides
        uses: ./.github/actions/prepare-for-slides

      - name: Build Slides
        run: xvfb-run ./gradlew :slides:build

      - name: Validate no local changes
        uses: ./.github/actions/no-local-changes

      - name: Publish Slides
        run: xvfb-run ./gradlew --stacktrace :slides:gitPublishPush
